# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [  
    {
        :name => "master",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.10.10",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "webapp-front",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.10.11",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "webapp-back",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.10.12",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "webapp-db",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.10.13",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "qa-server",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.10.14",
        :mem => "4048",
        :cpu => "1"
    }
]

Vagrant.configure("2") do |config|
 
  servers.each do |set|
      config.vm.define set[:name] do |config|

          config.vm.box = set[:box]
          config.vm.hostname = set[:name]
          config.vm.network :private_network, ip: set[:eth1]
          
          config.vm.provider "virtualbox" do |vb|
            vb.cpus   =  set[:cpu]
            vb.memory =  set[:mem]
            vb.name   =  set[:name]
          end
          

        #   config.vm.provision 'ansible_local'  do  |ansible|
        #     ansible.galaxy_role_file = 'requirements.yml'
        #     ansible.galaxy_roles_path = '/vagrant/roles'
        #     ansible.galaxy_command = 'ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}'
        #     ansible.playbook = 'playbook-kubernetes.yml'        
        #   end
     end

  end

end